export const GET_WALLETS = 'GET_WALLETS';
export const SET_SELECTED_WALLET = 'SET_SELECTED_WALLET';
export const GET_WALLET_TRANSACTIONS = 'GET_WALLET_TRANSACTIONS';
export const RESET_WALLET_DETAILS = 'RESET_WALLET_DETAILS';

export const WALLETS_REQUEST_PENDING = 'WALLETS_REQUEST_PENDING';
export const WALLETS_REQUEST_FULFILLED = 'WALLETS_REQUEST_FULFILLED';
